nav:
  - index.md
  - Fundamentals: math
  - nlp.md
  - Initializers.md
  - optimizers
  - regularization.md
  - convolution.md
  - max_pool.md
  - batch_norm.md
  - rnn.md
  - lstm.md
  - tokenization
  - models
  - papers
  - "*/"